### PR TITLE
fix to #367 for screenshots and savestates

### PR DESCRIPTION
**Pull request by Jcw87**
Fixes the primary issues in #379

### CODE REVIEW

**Comment by Jcw87** [comment]
Also added a fix for the game switching graphical bugs that only seemed to afflict ParaLLEl.

**Comment by Jamiras** [comment]
I've verified these changes fix the issues I mentioned in #379

> 1. Mupen64plus-Next > Mupen64plus-Next : seems fine
> 2. Mupen64plus-Next > ParaLLEl : rendering issues, video failure on screenshot
> 3. ParaLLEl -> Mupen64plus-Next : seems fine
> 4. ParaLLEl -> ParaLLEl : rendering issues, video failure on screenshot.

I was able to successfully take a screenshot after each of these paths. Thanks!

**Comment by Jamiras** [comment]
However, if I switch from ParaLLEl to ParaLLEl or Mupen64plus-Next (bullets 3 and 4) just after Mario's face appears, it crashes. The stacktrace is entirely in parallel_n64_libretro.dll, which suggests stack corruption. I don't think it's related to the GL context stuff, but if you wouldn't mind taking a look, I'd appreciate it.

**Review by Jamiras — APPROVED** [review]

**Comment by Jcw87** [comment]
Does that crash occur if both of my PRs are merged? The other one fixes a crash when shutting down ParaLLEl and attempting to start any core.

**Comment by Jamiras** [comment]
> Does that crash occur if both of my PRs are merged? The other one fixes a crash when shutting down ParaLLEl and attempting to start any core.

It does not. I did not realize there were two PRs. Thanks.

I wonder if there's a similar unflushed error causing RetroArch to crash.

**Pull request merged**
