### PR TITLE
support for multi-file games

### PR DESCRIPTION
**Pull request by Jamiras**

### CODE REVIEW

**Comment by rzumer** [comment]
Two general comments at first glance:
1. 10 discs seems excessive. Even half of that seems to be more than enough. What is the reason for having this many?
2. Hashing only the primary executable makes this very open to abuse, by tampering with data. I expect that hacks that modify balance would be likely to be detected as valid.

**Comment by Jamiras** [comment]
1. It's consistent with recent items, and save states. I agree that it's excessive, but we have to allocate a maximum limit for a worst-case scenario. Ideally, the unused items would be hidden instead of just left "Empty", but the WinAPI doesn't provide an easy way to do that - to hide items you have to delete them, so I thought I'd leave that for a separate PR.

2. This is the compromise we've adopted to support RetroArch. They refuse to let us hash more than 64MB. 
```
      /* size limit */
      if (coro->count > CHEEVOS_MB(64))
         coro->count = CHEEVOS_MB(64);
```
If we could just hash the entire CD, that would have been done quite some time ago. The alternative, which was briefly examined is the other extreme - where we just hash the serial number/volume name of the disc.

The executable file on the set of discs I tested ranged from 300KB to 1200KB, well below the 64MB limit, and ensures the player isn't modfiying the code. This solution has been discussed in the admin channel and with both caricatur and leiradel. Modifying the data files _is_ a possibility, but most existing hacks modify both the code and the data, so there would be a very small subset of users who would even try. On the other hand, this does open up the possibility of applying purely graphical hacks without requiring them be specifically linked, which could be considered a good thing (there's bound to be a nude Tomb Raider patch floating around somewhere).

Full disclosure: we don't expect RetroArch to hash CDs as they're swapped out, which leads to even bigger validation concerns.

This solution also works with real CDs as the actual executable file contents are being hashed. When stored in a bin/cue, there's a lot of additional metadata (every 2048 bytes of actual data takes 2352 bytes in the bin file). Hashing the bin directly would include that metadata. Note that RALibRetro doesn't currently support real CDs, but I've generated the hash of a file on a real CD and it matches the result generated by RALibRetro.

**Comment by rzumer** [comment]
It is a good solution, and as supported by your last comment, preferable to full file hashing, if cheating is not a significant concern. It sounds like getting the system supported (by "RA standards") is considered more important than curbing cheating. I don't disagree personally, but I am sure some people will find that to be a problem.

**Comment by Jamiras** [comment]
I went ahead and made the changes to dynamically populate the CD-ROM menu. It wasn't as complicated as I expected.

**Pull request merged**
