### PR TITLE
using bin directory for DLLs and cores

### PR DESCRIPTION
**Pull request by meleu**
No changes in the code, just adding all files needed to run RALibretro. This will make it easier to build `.zip` packs and release them for users to download.

If this PR here is approved by @leiradel I'll try to tweak the Makefile so we can build the `.zip` package using a `make pack` command.

### CODE REVIEW

**Comment by meleu** [comment]
The idea is more to be able to build a pack with all needed files to run RALibretro. And the `.dll` files are needed.

Are you concerned about, let's say, "legal implications" of keeping those `.dll` files or is it something else?

**Comment by leiradel** [comment]
> Are you concerned about, let's say, "legal implications" of keeping those .dll files or is it something else?

Not, it's just that there are a lot of files that exist or are created by RALibretro in the `bin` folder that will pollute the list of unstaged files, like screenshots, game states, and configuration files. Those should be in the `.gitignore`.

**Comment by meleu** [comment]
Oh yeah... Regarding `.gitignore` I agree, I'll try to list more files to be ignored. But I was actually replying to this part:

> I think we just want the ones in `bin/Cores` to be part of the repository.

I understood it as "we do not want those `dll`s to be part of the repository".

Just to be sure, let me ask more directly: are you OK about having those `dll`s as part of the repo?

**Comment by meleu** [comment]
can you check if it's fine now @leiradel ?

**Comment by meleu** [comment]
In this last commit I added the rule `pack` to the Makefile. Therefore `make pack` can be used to build a `.zip` pack with all needed files to run RALibretro.

**Comment by meleu** [comment]
@leiradel one more try for the `.gitignore`. Can you check if GitKraken works fine with it?

And in the last commit I'm making the `make zip` save the `RALibretro-*.zip` file in the root directory.

**Comment by leiradel** [comment]
@meleu can you change the PR to merge into the develop branch? Thanks.

**Comment by meleu** [comment]
@leiradel done!

**Pull request merged**
